# Generated by Django 6.0.7 on 2026-07-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(db_index=True, default='website', max_length=64)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('value', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('site', 'name'),
                'constraints': [models.UniqueConstraint(fields=('site', 'name'), name='core_setting_site_name_uniq')],
            },
        ),
    ]
