# Generated by Django 6.0.7 on 2026-07-20 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('make_payment', models.CharField(choices=[('one_time', 'One time'), ('per_period', 'Per period')], default='per_period', max_length=20)),
                ('hourly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('daily_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('weekly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('minimum_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('minimum_months', models.PositiveIntegerField(blank=True, null=True)),
                ('has_multiple_items', models.BooleanField(default=False)),
                ('total_items', models.PositiveIntegerField(default=1)),
                ('total_sold', models.PositiveIntegerField(default=0)),
                ('selling_points', models.JSONField(blank=True, default=list)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('post_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.CharField(blank=True, max_length=50)),
                ('longitude', models.CharField(blank=True, max_length=50)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('owner_delivery_pickup', models.BooleanField(default=False)),
                ('owner_delivery_pickup_km', models.CharField(blank=True, max_length=50)),
                ('owner_delivery_pickup_cost', models.CharField(blank=True, max_length=50)),
                ('owner_pickup', models.BooleanField(default=False)),
                ('owner_postage', models.BooleanField(default=False)),
                ('owner_postage_cost', models.CharField(blank=True, max_length=50)),
                ('which_tnc', models.CharField(choices=[('default', 'Default'), ('own', 'Own')], default='default', max_length=20)),
                ('tnc', models.TextField(blank=True)),
                ('available_on_days', models.JSONField(blank=True, default=list)),
                ('starting_hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ending_hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('not_availability', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_admin_approved', models.BooleanField(default=False)),
                ('created_by', models.PositiveSmallIntegerField(choices=[(0, 'Web'), (1, 'App'), (2, 'Import'), (3, 'CSV import'), (4, 'API import')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('is_sold', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
