# Generated by Django 6.0.7 on 2026-07-20 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_label', models.CharField(editable=False, max_length=32, unique=True)),
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('user_address', models.TextField(blank=True)),
                ('product_variant_sku', models.JSONField(blank=True, default=list)),
                ('description_while_renting', models.TextField(blank=True)),
                ('description_while_return', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_due_date', models.DateField(blank=True, null=True)),
                ('plan_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('period', models.PositiveIntegerField(default=1)),
                ('make_payment', models.CharField(choices=[('one_time', 'One time'), ('per_period', 'Per period')], default='per_period', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pickup_address', models.TextField(blank=True)),
                ('return_address', models.TextField(blank=True)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('delivery_by', models.CharField(choices=[('renter', 'Renter pickup'), ('owner', 'Owner delivery'), ('postage', 'Postage')], default='renter', max_length=20)),
                ('delivery_address', models.TextField(blank=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('cancellation_comment', models.TextField(blank=True)),
                ('owner_cancellation_notes', models.TextField(blank=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order_status', models.CharField(choices=[('new-order', 'New order'), ('delivered', 'Delivered'), ('request-return', 'Return requested'), ('returned', 'Returned'), ('request-cancellation', 'Cancellation requested'), ('cancelled', 'Cancelled')], db_index=True, default='new-order', max_length=32)),
                ('is_autopay_enabled', models.BooleanField(default=False)),
                ('autopay_disabled_at', models.DateTimeField(blank=True, null=True)),
                ('requested_bill_at', models.DateTimeField(blank=True, null=True)),
                ('received_bill_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('last_autopaid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
